# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os
import pickle
from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage

from app.config import DB_USERNAME, DB_PASSWORD, DB, DB_HOST
from app.constants import PupilEnum
from app.models import Employee, WorkerController, DBConnector

__all__ = ['init_gui']

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

# files constants
FILE_NAME = 'file.txt'
FILE_PATH = Path(__file__).parent / Path('./workdir')


class Gui:

    def init_gui(self):
        self.window = Tk()
        self.window.geometry("640x480")
        self.window.configure(bg="#22282C")
        self.window.resizable(False, False)

        self.canvas = Canvas(
            self.window,
            bg="#22282C",
            height=480,
            width=640,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        self.canvas.place(x=0, y=0)
        self.canvas.create_rectangle(
            0.0,
            0.0,
            49.0,
            480.0,
            fill="#2D353D",
            outline="")

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.window.destroy(),
            relief="flat"
        )
        self.button_1.place(
            x=0.0,
            y=438.0,
            width=49.0,
            height=42.0
        )

        self.canvas.create_rectangle(
            50.0,
            209.0,
            641.0,
            211.0,
            fill="#4C5154",
            outline="")

        self.button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        self.button_2 = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add_worker(),
            relief="flat"
        )
        self.button_2.place(
            x=471.0,
            y=172.0,
            width=140.0,
            height=25.0
        )

        self.button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        self.button_3 = Button(
            image=self.button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.button_3_click(),
            relief="flat"
        )
        self.button_3.place(
            x=471.0,
            y=256.0,
            width=140.0,
            height=25.0
        )

        self.button_image_10 = PhotoImage(
            file=relative_to_assets("button_10.png"))
        self.button_10 = Button(
            image=self.button_image_10,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.button_10_click(),
            relief="flat"
        )
        self.button_10.place(
            x=471.0,
            y=287.0,
            width=140.0,
            height=25.0
        )

        self.button_image_12 = PhotoImage(
            file=relative_to_assets("button_12.png"))
        self.db_connect_button = Button(
            text='Connect',
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.connect_click(),
            relief="flat"
        )
        self.db_connect_button.place(
            x=81.0,
            y=370.0,
            width=140.0,
            height=25.0
        )

        self.button_image_13 = PhotoImage(
            file=relative_to_assets("button_13.png"))
        self.db_file_connect_button = Button(
            text='Connect using file',
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.connect_using_file_click(),
            relief="flat"
        )
        self.db_file_connect_button.place(
            x=81.0,
            y=400.0,
            width=140.0,
            height=25.0
        )

        self.canvas.create_text(
            85.0,
            275.0,
            anchor="nw",
            text="Db name",
            fill="#FBFBFB",
            font=("Roboto", 14 * -1)
        )
        self.canvas.create_text(
            85.0,
            300.0,
            anchor="nw",
            text="User",
            fill="#FBFBFB",
            font=("Roboto", 14 * -1)
        )
        self.canvas.create_text(
            85.0,
            325.0,
            anchor="nw",
            text="Password",
            fill="#FBFBFB",
            font=("Roboto", 14 * -1)
        )

        self.entry_db_name = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_db_name.place(
            x=170.0,
            y=275.0,
            width=140.0,
            height=16.0
        )
        self.entry_user_name = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_user_name.place(
            x=170.0,
            y=300.0,
            width=140.0,
            height=16.0
        )
        self.entry_password = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_password.place(
            x=170.0,
            y=325.0,
            width=140.0,
            height=16.0
        )

        self.canvas.create_rectangle(
            471.0,
            53.0,
            611.0,
            83.0,
            fill="#4C5154",
            outline="")

        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            541.0,
            74.0,
            image=self.entry_image_1
        )
        self.entry_1 = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_1.place(
            x=471.0,
            y=65.0,
            width=140.0,
            height=16.0
        )

        self.canvas.create_text(
            476.0,
            56.0,
            anchor="nw",
            text="Position",
            fill="#FBFBFB",
            font=("Roboto", 8 * -1)
        )

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        entry_bg_2 = self.canvas.create_image(
            346.0,
            119.0,
            image=self.entry_image_2
        )
        self.entry_2 = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_2.place(
            x=276.0,
            y=110.0,
            width=140.0,
            height=16.0
        )

        self.canvas.create_rectangle(
            276.0,
            53.0,
            416.0,
            83.0,
            fill="#4C5154",
            outline="")

        self.canvas.create_rectangle(
            276.0,
            98.0,
            416.0,
            128.0,
            fill="#4C5154",
            outline="")

        self.canvas.create_text(
            280.0,
            101.0,
            anchor="nw",
            text="Specialization",
            fill="#FBFBFB",
            font=("Roboto", 8 * -1)
        )

        self.entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        entry_bg_3 = self.canvas.create_image(
            346.0,
            74.0,
            image=self.entry_image_3
        )
        self.entry_3 = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_3.place(
            x=276.0,
            y=65.0,
            width=140.0,
            height=16.0
        )

        self.canvas.create_text(
            280.0,
            56.0,
            anchor="nw",
            text="Grade class",
            fill="#FBFBFB",
            font=("Roboto", 8 * -1)
        )

        self.entry_image_4 = PhotoImage(
            file=relative_to_assets("entry_4.png"))
        entry_bg_4 = self.canvas.create_image(
            151.0,
            164.0,
            image=self.entry_image_4
        )
        self.entry_4 = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_4.place(
            x=81.0,
            y=155.0,
            width=140.0,
            height=16.0
        )

        self.canvas.create_rectangle(
            81.0,
            143.0,
            221.0,
            173.0,
            fill="#4C5154",
            outline="")

        self.canvas.create_rectangle(
            81.0,
            98.0,
            221.0,
            128.0,
            fill="#4C5154",
            outline="")

        self.canvas.create_rectangle(
            81.0,
            53.0,
            221.0,
            83.0,
            fill="#4C5154",
            outline="")

        self.canvas.create_text(
            86.0,
            146.0,
            anchor="nw",
            text="Sex",
            fill="#FBFBFB",
            font=("Roboto", 8 * -1)
        )

        self.entry_image_5 = PhotoImage(
            file=relative_to_assets("entry_5.png"))
        self.entry_bg_5 = self.canvas.create_image(
            150.0,
            119.0,
            image=self.entry_image_5
        )
        self.entry_5 = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_5.place(
            x=81.0,
            y=110.0,
            width=140.0,
            height=16.0
        )

        self.canvas.create_text(
            86.0,
            101.0,
            anchor="nw",
            text="Second name",
            fill="#FBFBFB",
            font=("Roboto", 8 * -1)
        )

        self.entry_image_6 = PhotoImage(
            file=relative_to_assets("entry_6.png"))
        self.entry_bg_6 = self.canvas.create_image(
            151.0,
            74.0,
            image=self.entry_image_6
        )
        self.entry_6 = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.entry_6.place(
            x=81.0,
            y=65.0,
            width=140.0,
            height=16.0
        )

        self.canvas.create_text(
            86.0,
            56.0,
            anchor="nw",
            text="First name",
            fill="#FBFBFB",
            font=("Roboto", 8 * -1)
        )

        self.canvas.create_text(
            304.0,
            14.0,
            anchor="nw",
            text="Creation",
            fill="#FBFBFB",
            font=("Roboto", 22 * -1)
        )

        self.db_id = Entry(
            bd=0,
            bg="#4C5154",
            highlightthickness=0
        )
        self.db_id.place(
            x=470.0,
            y=330.0,
            width=140.0,
            height=16.0
        )

    def __init__(self):
        self.maintainer = WorkerController()
        self.db_connector = DBConnector()
        self.init_gui()
        self.window.mainloop()

    def hide_main_screen(self):
        self.canvas.pack_forget()

    # Work with logic

    def add_worker(self):
        """ Добавляет сотрудника в список сотрудников """
        parsed = self.parse_fields()
        employee = Employee(
            position=parsed[PupilEnum.POSITION.value],
            specialization=parsed[PupilEnum.SPECIALIZATION.value],
            grade_class=parsed[PupilEnum.GRADE_CLASS.value],
            sex=parsed[PupilEnum.SEX.value],
            last_name=parsed[PupilEnum.LAST_NAME.value],
            first_name=parsed[PupilEnum.FIRST_NAME.value],
        )
        self.db_connector.insert_data(employee)
        # self.maintainer.append(employee)

    def parse_fields(self) -> dict:
        """ Получает данные из строк ввода """
        return {
            PupilEnum.POSITION.value: self.entry_1.get(),
            PupilEnum.SPECIALIZATION.value: self.entry_2.get(),
            PupilEnum.GRADE_CLASS.value: self.entry_3.get(),
            PupilEnum.SEX.value: self.entry_4.get(),
            PupilEnum.LAST_NAME.value: self.entry_5.get(),
            PupilEnum.FIRST_NAME.value: self.entry_6.get(),
        }

    def add_to_file(self):
        data = self.parse_fields()
        write_mode = 'wb' if os.path.exists(FILE_PATH) else 'wb+'

        with open(FILE_PATH, write_mode) as fw:
            pickle.dump(data, fw)

    def read_file(self):
        with open(FILE_PATH, 'rb') as fr:
            file_lines = pickle.load(fr)

        print(f'Content of file: {FILE_NAME}')
        for count, (key, value) in enumerate(file_lines.items()):
            print(f'line {count}: {key}: {value}')

    def clear_file(self):
        with open(FILE_PATH, 'w'): pass

    def connect_click(self):
        db = self.entry_db_name.get()
        db_username = self.entry_user_name.get()
        db_password = self.entry_password.get()

        # self.db_connector.connect(DB, DB_USERNAME, DB_PASSWORD)
        self.db_connector.connect(db, db_username, db_password)

    def connect_using_file_click(self):
        pass

    def button_3_click(self):
        self.db_connector.show_data()

    def button_10_click(self):
        self.db_connector.remove_data(self.db_id.get())


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def init_gui():
    Gui()
